server:
  port: ${PORT:80}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
      routes:
        - id: products
          uri: ${PRODUCTS_HOST:http://localhost:8080}
          predicates:
            - Path=/v1/products
        - id: stores
          uri: ${STORES_HOST:http://localhost:8081}
          predicates:
            - Path=/v1/stores
