spring:
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: *
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: update
