server:
  port: 8081

spring:
  webflux:
    base-path: /v1
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:example@127.0.0.1:27017}
      database: chaos
  jackson:
    default-property-inclusion: NON_NULL

chaos:
  monkey:
    watcher:
      restController: true
      repository: true

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: chaosmonkey
