spring:
  cloud:
    function:
      definition: sampleConsumer;sampleSeekConsumer
    stream:
      bindings:
        sampleConsumer-in-0:
          destination: sample-topic
          group: sample-consumer-0
          binder: kafka
          consumer:
            ackMode: RECORD
            startOffset: latest
        sampleSeekConsumer-in-0:
          destination: sample-topic
          group: sample-consumer-1
          binder: kafka
          consumer:
            ackMode: RECORD
      kafka:
        binder:
          autoCreateTopics: false
          brokers:
            - localhost:9092
          configuration:
            security.protocol: PLAINTEXT

sample:
  kafka:
    seekList:
      - binding: sampleSeekConsumer-in-0
        timestamp: 1647837636933
